### PR TITLE
Added code to implement App.rb

### PR DESCRIPTION
**Pull request by JevonMckenzie**
Hi: Please consider my implementation of the App.rb code.

### CODE REVIEW

**Comment by cyhsutw** [comment]
Hi Jevon,

The method you implemented seems not consistent with the [spec](https://github.com/ISS-Security/class-SEC-HW/blob/master/credit_card_api.md#3-sinatra-app-apprb).

You may choose one of the following routes to implement 
- `/`: which return a message that your service is running
- `/api/v1/credit_card/validate`: which validates credit card numbers using the Luhn algorithm

Please update it and push to this branch again (no need to open a new PR).

Cheers :beers:

**Comment by amonmoce** [comment]
I don't think you have to convert it into json. Just make card.validate_checksum ... and it's okay.

**Comment by amonmoce** [comment]
I think this part
{
   card: number,
    validated: card.validate_checksum
}
should be replaced by card.validate_checksum

**Comment by cyhsutw** [comment]
:beers:  :+1:

**Comment by cyhsutw** [comment]
:beers:

**Comment by amonmoce** [comment]
you deleted the branch ?

**Comment by cyhsutw** [comment]
Yep, I usually do this after merging the branch, since all of the commit logs can be found even the branch is deleted.

Also, the [`network`](https://github.com/SERVSEC-JAC/Credit-Card-API/network) shown on GitHub will show all of the branches.

I can restore the branch if you'd like me to :smiley:

**Pull request merged**
