### PR TITLE
TODO: Basic User Auth

### PR DESCRIPTION
**Pull request by cyhsutw**
Click [here](https://github.com/ISS-Security/class-SEC-HW/blob/authentication/credit_card_api.md#e-basic-user-authentication) for full specs.

#### TODOs

1. Finish `model/user.rb`

2. Finish `app.rb` and `helpers/credit_card_api_helper.rb`
3. Finish all views `views/*.haml`

Open a new branch based on `develop` and start working, when done, open a PR.

@JevonMckenzie & @amonmoce, please leave a comment about what you're going to work on, and I'll take the remaining part.

And please finish your part before **2015/05/14 21:00**.

### CODE REVIEW

**Comment by amonmoce** [comment]
I can do the helpers part

**Comment by cyhsutw** [comment]
@amonmoce Did you mean the second part? 
> Finish app.rb and helpers/credit_card_api_helper.rb

**Comment by amonmoce** [comment]
@cyhsutw  Yes ....

**Comment by JevonMckenzie** [comment]
user.rb complete. Let me know if there is anything else you need me to do

**Comment by cyhsutw** [comment]
@JevonMckenzie : 
Please merge #15 when you're done.
Also, merge #13 to `master`.

This will deploy the project to Heroku.

After deployment, run migration on Heroku using

```shell
$ heroku run rake db:migrate --app credit-card-api
```

**Pull request merged**
